name: seniguard
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_lints: ^2.0.0
  flutter:
    sdk: flutter
  kakao_flutter_sdk_user: ^1.9.5  # 카카오 로그인 API 패키지
  logger: ^1.0.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0  # 최신 버전으로 지정하세요
  # STT, TTS 지정
  speech_to_text: ^6.6.2
  permission_handler: ^10.2.0
  google_maps_flutter: any
  geolocator: ^10.0.0
  flutter_polyline_points: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
